Document zlib install
brefphp/aws-lambda-layers pull request #113
Opened 2023-08-31 12:16 UTC by mnapoli

Follow-up for #110

2023-08-31 12:25 UTC, GrahamCampbell commented on php-83/Dockerfile
> +# Can be removed once Lambda updates their version.
I don't think they ever will, for BC reasons. We'll likely have to wait till Lambda gets AL 2023, if that ever happens. ;)

2023-08-31 12:26 UTC, mnapoli commented on php-83/Dockerfile
> +# Can be removed once Lambda updates their version.
@GrahamCampbell yep these are my notes for AL2023 😄

2023-08-31 12:49 UTC, GrahamCampbell requested changes

2023-08-31 12:49 UTC, GrahamCampbell commented on php-80/Dockerfile
> +    curl -Ls http://zlib.net/zlib-${VERSION_ZLIB}.tar.xz \
We could try `https://github.com/madler/zlib/releases/download/v${VERSION_ZLIB}/zlib-${VERSION_ZLIB}.tar.gz` instead?

2023-08-31 13:11 UTC, GrahamCampbell requested changes

2023-08-31 13:11 UTC, GrahamCampbell commented on php-80/Dockerfile
> +    curl -Ls https://github.com/madler/zlib/releases/download/v${VERSION_ZLIB}/zlib-${VERSION_ZLIB}.tar.gz \
oh, whoops. that is .gz, but the extract command expends .xz

2023-08-31 15:56 UTC, mnapoli commented on php-80/Dockerfile
> -    --64
@GrahamCampbell I removed this line (after reading https://github.com/madler/zlib/issues/143) at it seemed to do the trick. Do you see any reason to be worried?

If not I'll merge and release.

2023-08-31 17:27 UTC, GrahamCampbell commented on php-80/Dockerfile
> -    --64
Ah yeh, I think i did something similar when making vapor work with arm. This is fine. 👍

2023-08-31 17:27 UTC, GrahamCampbell approved these changes
Thanks for finishing off my jank.

2023-09-01 04:34 UTC, GrahamCampbell commented on php-80/Dockerfile
> +    curl -Ls https://github.com/madler/zlib/releases/download/v${VERSION_ZLIB}/zlib-${VERSION_ZLIB}.tar.gz \
We could also just use the `.tar.xz` version of this URL, to keep the extract command the same.

2023-09-01 07:38 UTC, merged